---
title: "hw1"
author: "Mandi Ward, Zach Farley & Esme Castro"
date: "2/14/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(gghighlight)
library(scales)
library(colorspace)
library(ggplot2)
library(ggrepel)
library(ggtext)
```

## Reading in the data
```{r}
transit_cost <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-01-05/transit_cost.csv')

# first read in the data
#d <- readr::read_csv(here::here("data", "crime.csv"))

# write it out as a parquet file
#arrow::write_parquet(d, here::here("data", "crime.parquet"))

# read it in again
crime <- arrow::read_parquet(here::here("data", "crime.parquet")) %>% 
  janitor::clean_names()
```

## Question 1
```{r reproduce-plot}
country_codes <- countrycode::codelist %>% 
  select(country_name = country.name.en, country = ecb)


transit_cost$real_cost <- as.double(transit_cost$real_cost) # convert chr to dbl

df <- merge(x = transit_cost, y = country_codes,
           by = "country", all = TRUE)                 ## merged datasets

df <- df[df$country %in% names(which(table(
  df$country)>=3)), ]                            ## removed occurrences > 3

q1 <- df %>% 
  group_by(country_name) %>% 
  summarise(mean = mean(real_cost),
            se = sd(real_cost) / sqrt(n()))

q1 %>% 
  filter(country_name != "NA") %>% 
  mutate(country_name = fct_reorder(country_name, mean)) %>% 
  ggplot(aes(mean, country_name)) +
  geom_linerange(aes(xmin = mean - 1.96 * se, xmax = mean + 1.96 * se),
                 color = "grey40") +
  geom_point(color = "cornflowerblue") +
  scale_x_continuous(labels = comma, expand = c(0, 0)) +
  coord_cartesian(xlim = c(0, 35000)) +
  theme_minimal() +
  theme(panel.grid.major.y = element_blank(),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.x = element_line(color = "gray85"),
        axis.title.x = element_text(face = "bold", size = 12),
        axis.text.y = element_text(size = 11),
        axis.text.x = element_text(size = 11),
        axis.title.y = element_text(face = "bold", size = 12),
        plot.title = element_text(hjust = -.5, size = 14),
        plot.caption = element_text(hjust = .5, size = 11)) +
  labs(x = "Real Cost (In millions of dollars)",
       y = "Country",
       title = "Cost to build transit systems vary across countries",
       caption = "Data provided through #tidytuesday by the Transit Costs Project")
```

## Question 2
```{r uncertainty-plot}
err <- q1 %>% 
  filter(country_name != "NA") %>% 
  mutate(country_name = fct_reorder(country_name, mean)) %>% 
  ggplot(aes(mean, country_name)) +
    geom_errorbarh(aes(xmin = mean - 2.58 * se, xmax = mean + 2.58 * se,
                 color = "99%"), width = 0.2, size = 0.8) + # 99% CI
    geom_errorbarh(aes(xmin = mean - 1.96 * se, xmax = mean + 1.96 * se,
                 color = "95%"), width = 0.2, size = 1.2) +  # 95% CI
    geom_errorbarh(aes(xmin = mean - 1.65 * se, xmax = mean + 1.65 * se,
                 color = "90%"), width = 0.2, size = 1.6) +   # 90% CI
  geom_point() +
  scale_x_continuous(labels = comma, expand = c(0, 0)) +
  coord_cartesian(xlim = c(0, 35000)) +
  theme_minimal() +
  theme(panel.grid.major.y = element_blank(),
        panel.grid.major.x = element_line(color = "gray85"),
        axis.title.x = element_text(face = "bold", size = 12),
        axis.title.y = element_text(face = "bold", size = 12),
        plot.title = element_text(hjust = -.45, size = 14),
        plot.subtitle = element_text(hjust = -.16),
        plot.caption = element_text(hjust = .5, size = 10)) +
  labs(x = "Real Cost (In millions of dollars)",
       y = "Country",
       title = "Cost to build transit systems vary across countries",
       subtitle = "Uncertainty of cost is provided",
       caption = "Data provided through #tidytuesday by the Transit Costs Project")

err +
  scale_color_manual("Confidence Interval",
                     values = c("#50af5b",
                                lighten("#50af5b", .5),
                                lighten("#50af5b", .8)))
```

## Question 3
```{r}
df1 <- transit_cost  %>%
   group_by(country, city)   #created new dataset with select varaibles 

to_label <- c("Ahmadabad", "Bangalore", "Chennai", "Delhi", "Gurgaon", "Hyderabad","Kochi", "Nagpur")

df2 <- df1 %>% 
  group_by(city, country) %>% 
   summarise(mean_length = mean(length), 
             mean_realcost = mean((real_cost)), 
             n = n()) #computed mean of varaibles

subset_cities <- df2 %>%
    filter(city %in% to_label)

df2 %>% 
ggplot(aes(mean_length, mean_realcost)) +
  geom_point(aes(size = n), color = "gray80") +
  geom_point(
    aes(size = n),
    data = filter(df2, str_detect(country, "IN")),
    color = "#9800b3"
  ) +
  scale_x_log10() +
  scale_y_log10(labels = scales::dollar) +
  theme(
    #legend.title = element_text("Number of transit systems"),
    legend.position = "bottom",
    legend.box.background = element_rect(color = NA)
    #legend.box.margin = margin(t = -0.5, unit = "cm")
  ) +
  scale_size_binned(
    name = "Number of transit systems", 
    breaks = c(5, 10, 20)
  ) +
  geom_text_repel(aes(label = city),
                  data = subset_cities,
                  min.segment.length = 0, 
                  box.padding = 0.75) +
  labs(title = "Longer transit systems tend to cost more",
         subtitle = "<span style = 'color: purple'>**India**</span> has among the most transit systems in the world",
         x = "Average length",
         y = "Average cost") +
  theme(plot.subtitle = ggtext::element_markdown()) 

```

## Question 5
```{r}
model_data <- crime %>% 
  mutate(neighborhood_id = relevel(factor(neighborhood_id), ref = "barnum"))

m <- glm(is_crime ~ neighborhood_id, 
         data = model_data,
         family = "binomial")

tidied <- broom::tidy(m)
```

```{r}
barnum_west <- tidied %>% 
  filter(term == "neighborhood_idbarnum-west")

barnum_west1 <- data.frame(
   x = qnorm(ppoints(16),
       mean = barnum_west$estimate,
       sd = barnum_west$std.error)
 ) %>% 
   mutate(less_crime = ifelse(x<=0, 
                              "#866892", 
                              "#24A981"))

ggplot(barnum_west1, aes(x)) +
  theme_minimal() +
  geom_dotplot(aes(fill = less_crime), 
               binwidth = 0.035) +
  scale_fill_identity(guide = "none") +
  geom_vline(xintercept = 0.000,
             color = "red",
             size = 1.5) +
  scale_y_continuous(name = "",
                     breaks = NULL
) +
  scale_x_continuous(name = "Difference in log odds of a crime being committed") +
  labs(title = "Probability of differential crime rates between neighborhoods",
        subtitle = "<span style = 'color: #866892'>**Barnum West**</span> compared to <span style = 'color: #24A981'>**Barnum**</span>",
       caption = "Each ball represents 5% probability") +
  theme(plot.subtitle = element_markdown(size = 14),       # added size here
        axis.title.x = element_text(size = 14),          # size here and below
        plot.title = element_text(size = 20),
        plot.caption = element_text(hjust = .75, size = 10))  # plus hjust here
```
